/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetUpcommingVisitDto from './GetUpcommingVisitDto';

/**
 * The GetAllVisitsDto model module.
 * @module model/GetAllVisitsDto
 * @version v0
 */
class GetAllVisitsDto {
    /**
     * Constructs a new <code>GetAllVisitsDto</code>.
     * @alias module:model/GetAllVisitsDto
     */
    constructor() { 
        
        GetAllVisitsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAllVisitsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAllVisitsDto} obj Optional instance to populate.
     * @return {module:model/GetAllVisitsDto} The populated <code>GetAllVisitsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAllVisitsDto();

            if (data.hasOwnProperty('visits')) {
                obj['visits'] = ApiClient.convertToType(data['visits'], [GetUpcommingVisitDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAllVisitsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAllVisitsDto</code>.
     */
    static validateJSON(data) {
        if (data['visits']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['visits'])) {
                throw new Error("Expected the field `visits` to be an array in the JSON data but got " + data['visits']);
            }
            // validate the optional field `visits` (array)
            for (const item of data['visits']) {
                GetUpcommingVisitDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/GetUpcommingVisitDto>} visits
 */
GetAllVisitsDto.prototype['visits'] = undefined;






export default GetAllVisitsDto;

