/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetAvailableSpecialistDto model module.
 * @module model/GetAvailableSpecialistDto
 * @version v0
 */
class GetAvailableSpecialistDto {
    /**
     * Constructs a new <code>GetAvailableSpecialistDto</code>.
     * @alias module:model/GetAvailableSpecialistDto
     */
    constructor() { 
        
        GetAvailableSpecialistDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAvailableSpecialistDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAvailableSpecialistDto} obj Optional instance to populate.
     * @return {module:model/GetAvailableSpecialistDto} The populated <code>GetAvailableSpecialistDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAvailableSpecialistDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('availableOffers')) {
                obj['availableOffers'] = ApiClient.convertToType(data['availableOffers'], ['Number']);
            }
            if (data.hasOwnProperty('availableTime')) {
                obj['availableTime'] = ApiClient.convertToType(data['availableTime'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAvailableSpecialistDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAvailableSpecialistDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['availableOffers'])) {
            throw new Error("Expected the field `availableOffers` to be an array in the JSON data but got " + data['availableOffers']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['availableTime'])) {
            throw new Error("Expected the field `availableTime` to be an array in the JSON data but got " + data['availableTime']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
GetAvailableSpecialistDto.prototype['id'] = undefined;

/**
 * @member {String} name
 */
GetAvailableSpecialistDto.prototype['name'] = undefined;

/**
 * @member {Array.<Number>} availableOffers
 */
GetAvailableSpecialistDto.prototype['availableOffers'] = undefined;

/**
 * @member {Array.<Number>} availableTime
 */
GetAvailableSpecialistDto.prototype['availableTime'] = undefined;






export default GetAvailableSpecialistDto;

