/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetAvailableTimeTableDto model module.
 * @module model/GetAvailableTimeTableDto
 * @version v0
 */
class GetAvailableTimeTableDto {
    /**
     * Constructs a new <code>GetAvailableTimeTableDto</code>.
     * @alias module:model/GetAvailableTimeTableDto
     */
    constructor() { 
        
        GetAvailableTimeTableDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAvailableTimeTableDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAvailableTimeTableDto} obj Optional instance to populate.
     * @return {module:model/GetAvailableTimeTableDto} The populated <code>GetAvailableTimeTableDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAvailableTimeTableDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAvailableTimeTableDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAvailableTimeTableDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['time'] && !(typeof data['time'] === 'string' || data['time'] instanceof String)) {
            throw new Error("Expected the field `time` to be a primitive type in the JSON string but got " + data['time']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
GetAvailableTimeTableDto.prototype['id'] = undefined;

/**
 * @member {Date} date
 */
GetAvailableTimeTableDto.prototype['date'] = undefined;

/**
 * @member {String} time
 */
GetAvailableTimeTableDto.prototype['time'] = undefined;






export default GetAvailableTimeTableDto;

