/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PersonDto from './PersonDto';

/**
 * The GetSpecialistsDto model module.
 * @module model/GetSpecialistsDto
 * @version v0
 */
class GetSpecialistsDto {
    /**
     * Constructs a new <code>GetSpecialistsDto</code>.
     * @alias module:model/GetSpecialistsDto
     */
    constructor() { 
        
        GetSpecialistsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSpecialistsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSpecialistsDto} obj Optional instance to populate.
     * @return {module:model/GetSpecialistsDto} The populated <code>GetSpecialistsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSpecialistsDto();

            if (data.hasOwnProperty('persons')) {
                obj['persons'] = ApiClient.convertToType(data['persons'], [PersonDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetSpecialistsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetSpecialistsDto</code>.
     */
    static validateJSON(data) {
        if (data['persons']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['persons'])) {
                throw new Error("Expected the field `persons` to be an array in the JSON data but got " + data['persons']);
            }
            // validate the optional field `persons` (array)
            for (const item of data['persons']) {
                PersonDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/PersonDto>} persons
 */
GetSpecialistsDto.prototype['persons'] = undefined;






export default GetSpecialistsDto;

