/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostOfferDto model module.
 * @module model/PostOfferDto
 * @version v0
 */
class PostOfferDto {
    /**
     * Constructs a new <code>PostOfferDto</code>.
     * @alias module:model/PostOfferDto
     */
    constructor() { 
        
        PostOfferDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostOfferDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostOfferDto} obj Optional instance to populate.
     * @return {module:model/PostOfferDto} The populated <code>PostOfferDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostOfferDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('promo')) {
                obj['promo'] = ApiClient.convertToType(data['promo'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('offerCategoryId')) {
                obj['offerCategoryId'] = ApiClient.convertToType(data['offerCategoryId'], 'Number');
            }
            if (data.hasOwnProperty('privateOffer')) {
                obj['privateOffer'] = ApiClient.convertToType(data['privateOffer'], 'Boolean');
            }
            if (data.hasOwnProperty('nfz')) {
                obj['nfz'] = ApiClient.convertToType(data['nfz'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostOfferDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostOfferDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['promo'] && !(typeof data['promo'] === 'string' || data['promo'] instanceof String)) {
            throw new Error("Expected the field `promo` to be a primitive type in the JSON string but got " + data['promo']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
PostOfferDto.prototype['name'] = undefined;

/**
 * @member {String} promo
 */
PostOfferDto.prototype['promo'] = undefined;

/**
 * @member {Number} price
 */
PostOfferDto.prototype['price'] = undefined;

/**
 * @member {Number} offerCategoryId
 */
PostOfferDto.prototype['offerCategoryId'] = undefined;

/**
 * @member {Boolean} privateOffer
 */
PostOfferDto.prototype['privateOffer'] = undefined;

/**
 * @member {Boolean} nfz
 */
PostOfferDto.prototype['nfz'] = undefined;






export default PostOfferDto;

