/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostVisitDto model module.
 * @module model/PostVisitDto
 * @version v0
 */
class PostVisitDto {
    /**
     * Constructs a new <code>PostVisitDto</code>.
     * @alias module:model/PostVisitDto
     */
    constructor() { 
        
        PostVisitDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostVisitDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostVisitDto} obj Optional instance to populate.
     * @return {module:model/PostVisitDto} The populated <code>PostVisitDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostVisitDto();

            if (data.hasOwnProperty('doctorId')) {
                obj['doctorId'] = ApiClient.convertToType(data['doctorId'], 'Number');
            }
            if (data.hasOwnProperty('timeTableId')) {
                obj['timeTableId'] = ApiClient.convertToType(data['timeTableId'], 'Number');
            }
            if (data.hasOwnProperty('serviceId')) {
                obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'Number');
            }
            if (data.hasOwnProperty('place')) {
                obj['place'] = ApiClient.convertToType(data['place'], 'String');
            }
            if (data.hasOwnProperty('refferalNumber')) {
                obj['refferalNumber'] = ApiClient.convertToType(data['refferalNumber'], 'String');
            }
            if (data.hasOwnProperty('home')) {
                obj['home'] = ApiClient.convertToType(data['home'], 'Boolean');
            }
            if (data.hasOwnProperty('nfz')) {
                obj['nfz'] = ApiClient.convertToType(data['nfz'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostVisitDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostVisitDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['place'] && !(typeof data['place'] === 'string' || data['place'] instanceof String)) {
            throw new Error("Expected the field `place` to be a primitive type in the JSON string but got " + data['place']);
        }
        // ensure the json data is a string
        if (data['refferalNumber'] && !(typeof data['refferalNumber'] === 'string' || data['refferalNumber'] instanceof String)) {
            throw new Error("Expected the field `refferalNumber` to be a primitive type in the JSON string but got " + data['refferalNumber']);
        }

        return true;
    }


}



/**
 * @member {Number} doctorId
 */
PostVisitDto.prototype['doctorId'] = undefined;

/**
 * @member {Number} timeTableId
 */
PostVisitDto.prototype['timeTableId'] = undefined;

/**
 * @member {Number} serviceId
 */
PostVisitDto.prototype['serviceId'] = undefined;

/**
 * @member {String} place
 */
PostVisitDto.prototype['place'] = undefined;

/**
 * @member {String} refferalNumber
 */
PostVisitDto.prototype['refferalNumber'] = undefined;

/**
 * @member {Boolean} home
 */
PostVisitDto.prototype['home'] = undefined;

/**
 * @member {Boolean} nfz
 */
PostVisitDto.prototype['nfz'] = undefined;






export default PostVisitDto;

