/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostMarkDto model module.
 * @module model/PostMarkDto
 * @version v0
 */
class PostMarkDto {
    /**
     * Constructs a new <code>PostMarkDto</code>.
     * @alias module:model/PostMarkDto
     * @param title {String} 
     * @param description {String} 
     * @param comment {String} 
     * @param doctorId {Number} 
     */
    constructor(title, description, comment, doctorId) { 
        
        PostMarkDto.initialize(this, title, description, comment, doctorId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, description, comment, doctorId) { 
        obj['title'] = title;
        obj['description'] = description;
        obj['comment'] = comment;
        obj['doctorId'] = doctorId;
    }

    /**
     * Constructs a <code>PostMarkDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostMarkDto} obj Optional instance to populate.
     * @return {module:model/PostMarkDto} The populated <code>PostMarkDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostMarkDto();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('doctorId')) {
                obj['doctorId'] = ApiClient.convertToType(data['doctorId'], 'Number');
            }
            if (data.hasOwnProperty('mark')) {
                obj['mark'] = ApiClient.convertToType(data['mark'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostMarkDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostMarkDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostMarkDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }

        return true;
    }


}

PostMarkDto.RequiredProperties = ["title", "description", "comment", "doctorId"];

/**
 * @member {String} title
 */
PostMarkDto.prototype['title'] = undefined;

/**
 * @member {String} description
 */
PostMarkDto.prototype['description'] = undefined;

/**
 * @member {String} comment
 */
PostMarkDto.prototype['comment'] = undefined;

/**
 * @member {Number} doctorId
 */
PostMarkDto.prototype['doctorId'] = undefined;

/**
 * @member {Number} mark
 */
PostMarkDto.prototype['mark'] = undefined;






export default PostMarkDto;

