/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PutDoctorDto model module.
 * @module model/PutDoctorDto
 * @version v0
 */
class PutDoctorDto {
    /**
     * Constructs a new <code>PutDoctorDto</code>.
     * @alias module:model/PutDoctorDto
     * @param firstName {String} 
     * @param lastName {String} 
     * @param specialityId {Number} 
     */
    constructor(firstName, lastName, specialityId) { 
        
        PutDoctorDto.initialize(this, firstName, lastName, specialityId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, specialityId) { 
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
        obj['specialityId'] = specialityId;
    }

    /**
     * Constructs a <code>PutDoctorDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PutDoctorDto} obj Optional instance to populate.
     * @return {module:model/PutDoctorDto} The populated <code>PutDoctorDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutDoctorDto();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('specialityId')) {
                obj['specialityId'] = ApiClient.convertToType(data['specialityId'], 'Number');
            }
            if (data.hasOwnProperty('degree')) {
                obj['degree'] = ApiClient.convertToType(data['degree'], 'String');
            }
            if (data.hasOwnProperty('degreeShort')) {
                obj['degreeShort'] = ApiClient.convertToType(data['degreeShort'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PutDoctorDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PutDoctorDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PutDoctorDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['degree'] && !(typeof data['degree'] === 'string' || data['degree'] instanceof String)) {
            throw new Error("Expected the field `degree` to be a primitive type in the JSON string but got " + data['degree']);
        }
        // ensure the json data is a string
        if (data['degreeShort'] && !(typeof data['degreeShort'] === 'string' || data['degreeShort'] instanceof String)) {
            throw new Error("Expected the field `degreeShort` to be a primitive type in the JSON string but got " + data['degreeShort']);
        }

        return true;
    }


}

PutDoctorDto.RequiredProperties = ["firstName", "lastName", "specialityId"];

/**
 * @member {String} firstName
 */
PutDoctorDto.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
PutDoctorDto.prototype['lastName'] = undefined;

/**
 * @member {Number} specialityId
 */
PutDoctorDto.prototype['specialityId'] = undefined;

/**
 * @member {String} degree
 */
PutDoctorDto.prototype['degree'] = undefined;

/**
 * @member {String} degreeShort
 */
PutDoctorDto.prototype['degreeShort'] = undefined;






export default PutDoctorDto;

