/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Doctor from './Doctor';
import Service from './Service';
import TimeTable from './TimeTable';

/**
 * The Visit model module.
 * @module model/Visit
 * @version v0
 */
class Visit {
    /**
     * Constructs a new <code>Visit</code>.
     * @alias module:model/Visit
     */
    constructor() { 
        
        Visit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Visit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Visit} obj Optional instance to populate.
     * @return {module:model/Visit} The populated <code>Visit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Visit();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('doctor')) {
                obj['doctor'] = Doctor.constructFromObject(data['doctor']);
            }
            if (data.hasOwnProperty('timeTable')) {
                obj['timeTable'] = TimeTable.constructFromObject(data['timeTable']);
            }
            if (data.hasOwnProperty('service')) {
                obj['service'] = Service.constructFromObject(data['service']);
            }
            if (data.hasOwnProperty('place')) {
                obj['place'] = ApiClient.convertToType(data['place'], 'String');
            }
            if (data.hasOwnProperty('refferalNumber')) {
                obj['refferalNumber'] = ApiClient.convertToType(data['refferalNumber'], 'String');
            }
            if (data.hasOwnProperty('home')) {
                obj['home'] = ApiClient.convertToType(data['home'], 'Boolean');
            }
            if (data.hasOwnProperty('nfz')) {
                obj['nfz'] = ApiClient.convertToType(data['nfz'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Visit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Visit</code>.
     */
    static validateJSON(data) {
        // validate the optional field `doctor`
        if (data['doctor']) { // data not null
          Doctor.validateJSON(data['doctor']);
        }
        // validate the optional field `timeTable`
        if (data['timeTable']) { // data not null
          TimeTable.validateJSON(data['timeTable']);
        }
        // validate the optional field `service`
        if (data['service']) { // data not null
          Service.validateJSON(data['service']);
        }
        // ensure the json data is a string
        if (data['place'] && !(typeof data['place'] === 'string' || data['place'] instanceof String)) {
            throw new Error("Expected the field `place` to be a primitive type in the JSON string but got " + data['place']);
        }
        // ensure the json data is a string
        if (data['refferalNumber'] && !(typeof data['refferalNumber'] === 'string' || data['refferalNumber'] instanceof String)) {
            throw new Error("Expected the field `refferalNumber` to be a primitive type in the JSON string but got " + data['refferalNumber']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Visit.prototype['id'] = undefined;

/**
 * @member {module:model/Doctor} doctor
 */
Visit.prototype['doctor'] = undefined;

/**
 * @member {module:model/TimeTable} timeTable
 */
Visit.prototype['timeTable'] = undefined;

/**
 * @member {module:model/Service} service
 */
Visit.prototype['service'] = undefined;

/**
 * @member {String} place
 */
Visit.prototype['place'] = undefined;

/**
 * @member {String} refferalNumber
 */
Visit.prototype['refferalNumber'] = undefined;

/**
 * @member {Boolean} home
 */
Visit.prototype['home'] = undefined;

/**
 * @member {Boolean} nfz
 */
Visit.prototype['nfz'] = undefined;






export default Visit;

