/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AssignServiceDto from './model/AssignServiceDto';
import Doctor from './model/Doctor';
import GetAllVisitsDto from './model/GetAllVisitsDto';
import GetAvailableSpecialistDto from './model/GetAvailableSpecialistDto';
import GetAvailableTimeTableDto from './model/GetAvailableTimeTableDto';
import GetSpecialistsDto from './model/GetSpecialistsDto';
import GetUpcommingVisitDto from './model/GetUpcommingVisitDto';
import LocalTime from './model/LocalTime';
import Mark from './model/Mark';
import MarkDto from './model/MarkDto';
import Offer from './model/Offer';
import OfferCategory from './model/OfferCategory';
import PersonDto from './model/PersonDto';
import PostDoctorDto from './model/PostDoctorDto';
import PostMarkDto from './model/PostMarkDto';
import PostOfferCategoryDto from './model/PostOfferCategoryDto';
import PostOfferDto from './model/PostOfferDto';
import PostServiceDto from './model/PostServiceDto';
import PostTimeTableDto from './model/PostTimeTableDto';
import PostVisitDto from './model/PostVisitDto';
import PutDoctorDto from './model/PutDoctorDto';
import Service from './model/Service';
import Speciality from './model/Speciality';
import TimeTable from './model/TimeTable';
import Visit from './model/Visit';
import VisitDto from './model/VisitDto';
import DoctorControllerApi from './api/DoctorControllerApi';
import HomeControllerApi from './api/HomeControllerApi';
import MarkControllerApi from './api/MarkControllerApi';
import OfferCategoryControllerApi from './api/OfferCategoryControllerApi';
import OfferControllerApi from './api/OfferControllerApi';
import ServiceControllerApi from './api/ServiceControllerApi';
import SpecialityControllerApi from './api/SpecialityControllerApi';
import TimeTableControllerApi from './api/TimeTableControllerApi';
import VisitControllerApi from './api/VisitControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AssignServiceDto model constructor.
     * @property {module:model/AssignServiceDto}
     */
    AssignServiceDto,

    /**
     * The Doctor model constructor.
     * @property {module:model/Doctor}
     */
    Doctor,

    /**
     * The GetAllVisitsDto model constructor.
     * @property {module:model/GetAllVisitsDto}
     */
    GetAllVisitsDto,

    /**
     * The GetAvailableSpecialistDto model constructor.
     * @property {module:model/GetAvailableSpecialistDto}
     */
    GetAvailableSpecialistDto,

    /**
     * The GetAvailableTimeTableDto model constructor.
     * @property {module:model/GetAvailableTimeTableDto}
     */
    GetAvailableTimeTableDto,

    /**
     * The GetSpecialistsDto model constructor.
     * @property {module:model/GetSpecialistsDto}
     */
    GetSpecialistsDto,

    /**
     * The GetUpcommingVisitDto model constructor.
     * @property {module:model/GetUpcommingVisitDto}
     */
    GetUpcommingVisitDto,

    /**
     * The LocalTime model constructor.
     * @property {module:model/LocalTime}
     */
    LocalTime,

    /**
     * The Mark model constructor.
     * @property {module:model/Mark}
     */
    Mark,

    /**
     * The MarkDto model constructor.
     * @property {module:model/MarkDto}
     */
    MarkDto,

    /**
     * The Offer model constructor.
     * @property {module:model/Offer}
     */
    Offer,

    /**
     * The OfferCategory model constructor.
     * @property {module:model/OfferCategory}
     */
    OfferCategory,

    /**
     * The PersonDto model constructor.
     * @property {module:model/PersonDto}
     */
    PersonDto,

    /**
     * The PostDoctorDto model constructor.
     * @property {module:model/PostDoctorDto}
     */
    PostDoctorDto,

    /**
     * The PostMarkDto model constructor.
     * @property {module:model/PostMarkDto}
     */
    PostMarkDto,

    /**
     * The PostOfferCategoryDto model constructor.
     * @property {module:model/PostOfferCategoryDto}
     */
    PostOfferCategoryDto,

    /**
     * The PostOfferDto model constructor.
     * @property {module:model/PostOfferDto}
     */
    PostOfferDto,

    /**
     * The PostServiceDto model constructor.
     * @property {module:model/PostServiceDto}
     */
    PostServiceDto,

    /**
     * The PostTimeTableDto model constructor.
     * @property {module:model/PostTimeTableDto}
     */
    PostTimeTableDto,

    /**
     * The PostVisitDto model constructor.
     * @property {module:model/PostVisitDto}
     */
    PostVisitDto,

    /**
     * The PutDoctorDto model constructor.
     * @property {module:model/PutDoctorDto}
     */
    PutDoctorDto,

    /**
     * The Service model constructor.
     * @property {module:model/Service}
     */
    Service,

    /**
     * The Speciality model constructor.
     * @property {module:model/Speciality}
     */
    Speciality,

    /**
     * The TimeTable model constructor.
     * @property {module:model/TimeTable}
     */
    TimeTable,

    /**
     * The Visit model constructor.
     * @property {module:model/Visit}
     */
    Visit,

    /**
     * The VisitDto model constructor.
     * @property {module:model/VisitDto}
     */
    VisitDto,

    /**
    * The DoctorControllerApi service constructor.
    * @property {module:api/DoctorControllerApi}
    */
    DoctorControllerApi,

    /**
    * The HomeControllerApi service constructor.
    * @property {module:api/HomeControllerApi}
    */
    HomeControllerApi,

    /**
    * The MarkControllerApi service constructor.
    * @property {module:api/MarkControllerApi}
    */
    MarkControllerApi,

    /**
    * The OfferCategoryControllerApi service constructor.
    * @property {module:api/OfferCategoryControllerApi}
    */
    OfferCategoryControllerApi,

    /**
    * The OfferControllerApi service constructor.
    * @property {module:api/OfferControllerApi}
    */
    OfferControllerApi,

    /**
    * The ServiceControllerApi service constructor.
    * @property {module:api/ServiceControllerApi}
    */
    ServiceControllerApi,

    /**
    * The SpecialityControllerApi service constructor.
    * @property {module:api/SpecialityControllerApi}
    */
    SpecialityControllerApi,

    /**
    * The TimeTableControllerApi service constructor.
    * @property {module:api/TimeTableControllerApi}
    */
    TimeTableControllerApi,

    /**
    * The VisitControllerApi service constructor.
    * @property {module:api/VisitControllerApi}
    */
    VisitControllerApi
};
