/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.DoctorControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DoctorControllerApi', function() {
    describe('addDoctor', function() {
      it('should call addDoctor successfully', function(done) {
        //uncomment below and update the code to test addDoctor
        //instance.addDoctor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('assignService', function() {
      it('should call assignService successfully', function(done) {
        //uncomment below and update the code to test assignService
        //instance.assignService(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDoctor', function() {
      it('should call deleteDoctor successfully', function(done) {
        //uncomment below and update the code to test deleteDoctor
        //instance.deleteDoctor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllDoctors', function() {
      it('should call getAllDoctors successfully', function(done) {
        //uncomment below and update the code to test getAllDoctors
        //instance.getAllDoctors(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAvailableSpecialists', function() {
      it('should call getAvailableSpecialists successfully', function(done) {
        //uncomment below and update the code to test getAvailableSpecialists
        //instance.getAvailableSpecialists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDoctor', function() {
      it('should call getDoctor successfully', function(done) {
        //uncomment below and update the code to test getDoctor
        //instance.getDoctor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDoctor1', function() {
      it('should call getDoctor1 successfully', function(done) {
        //uncomment below and update the code to test getDoctor1
        //instance.getDoctor1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMarksByDoctorId', function() {
      it('should call getMarksByDoctorId successfully', function(done) {
        //uncomment below and update the code to test getMarksByDoctorId
        //instance.getMarksByDoctorId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getServicesByDoctorId', function() {
      it('should call getServicesByDoctorId successfully', function(done) {
        //uncomment below and update the code to test getServicesByDoctorId
        //instance.getServicesByDoctorId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateDoctor', function() {
      it('should call updateDoctor successfully', function(done) {
        //uncomment below and update the code to test updateDoctor
        //instance.updateDoctor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
