/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.OfferCategoryControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OfferCategoryControllerApi', function() {
    describe('addOfferCategory', function() {
      it('should call addOfferCategory successfully', function(done) {
        //uncomment below and update the code to test addOfferCategory
        //instance.addOfferCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOfferCategory', function() {
      it('should call deleteOfferCategory successfully', function(done) {
        //uncomment below and update the code to test deleteOfferCategory
        //instance.deleteOfferCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllOfferCategorys', function() {
      it('should call getAllOfferCategorys successfully', function(done) {
        //uncomment below and update the code to test getAllOfferCategorys
        //instance.getAllOfferCategorys(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOfferCategory', function() {
      it('should call getOfferCategory successfully', function(done) {
        //uncomment below and update the code to test getOfferCategory
        //instance.getOfferCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateOfferCategory', function() {
      it('should call updateOfferCategory successfully', function(done) {
        //uncomment below and update the code to test updateOfferCategory
        //instance.updateOfferCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
