/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.SpecialityControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SpecialityControllerApi', function() {
    describe('createSpeciality', function() {
      it('should call createSpeciality successfully', function(done) {
        //uncomment below and update the code to test createSpeciality
        //instance.createSpeciality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSpeciality', function() {
      it('should call deleteSpeciality successfully', function(done) {
        //uncomment below and update the code to test deleteSpeciality
        //instance.deleteSpeciality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllSpecialities', function() {
      it('should call getAllSpecialities successfully', function(done) {
        //uncomment below and update the code to test getAllSpecialities
        //instance.getAllSpecialities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDoctorsBySpecialityId', function() {
      it('should call getDoctorsBySpecialityId successfully', function(done) {
        //uncomment below and update the code to test getDoctorsBySpecialityId
        //instance.getDoctorsBySpecialityId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSpeciality', function() {
      it('should call getSpeciality successfully', function(done) {
        //uncomment below and update the code to test getSpeciality
        //instance.getSpeciality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSpecialityByDoctorId', function() {
      it('should call getSpecialityByDoctorId successfully', function(done) {
        //uncomment below and update the code to test getSpecialityByDoctorId
        //instance.getSpecialityByDoctorId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSpeciality', function() {
      it('should call updateSpeciality successfully', function(done) {
        //uncomment below and update the code to test updateSpeciality
        //instance.updateSpeciality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
