/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.TimeTableControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TimeTableControllerApi', function() {
    describe('addTimeTable', function() {
      it('should call addTimeTable successfully', function(done) {
        //uncomment below and update the code to test addTimeTable
        //instance.addTimeTable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTimeTable', function() {
      it('should call deleteTimeTable successfully', function(done) {
        //uncomment below and update the code to test deleteTimeTable
        //instance.deleteTimeTable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllTimeTables', function() {
      it('should call getAllTimeTables successfully', function(done) {
        //uncomment below and update the code to test getAllTimeTables
        //instance.getAllTimeTables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAvailableTimeTables', function() {
      it('should call getAvailableTimeTables successfully', function(done) {
        //uncomment below and update the code to test getAvailableTimeTables
        //instance.getAvailableTimeTables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTimeTable', function() {
      it('should call getTimeTable successfully', function(done) {
        //uncomment below and update the code to test getTimeTable
        //instance.getTimeTable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTimeTable', function() {
      it('should call updateTimeTable successfully', function(done) {
        //uncomment below and update the code to test updateTimeTable
        //instance.updateTimeTable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
