/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.VisitControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VisitControllerApi', function() {
    describe('addVisit', function() {
      it('should call addVisit successfully', function(done) {
        //uncomment below and update the code to test addVisit
        //instance.addVisit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bookVisit', function() {
      it('should call bookVisit successfully', function(done) {
        //uncomment below and update the code to test bookVisit
        //instance.bookVisit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVisit', function() {
      it('should call deleteVisit successfully', function(done) {
        //uncomment below and update the code to test deleteVisit
        //instance.deleteVisit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllVisits', function() {
      it('should call getAllVisits successfully', function(done) {
        //uncomment below and update the code to test getAllVisits
        //instance.getAllVisits(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllVisitsForPatient', function() {
      it('should call getAllVisitsForPatient successfully', function(done) {
        //uncomment below and update the code to test getAllVisitsForPatient
        //instance.getAllVisitsForPatient(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNearestVisitForPatient', function() {
      it('should call getNearestVisitForPatient successfully', function(done) {
        //uncomment below and update the code to test getNearestVisitForPatient
        //instance.getNearestVisitForPatient(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVisit', function() {
      it('should call getVisit successfully', function(done) {
        //uncomment below and update the code to test getVisit
        //instance.getVisit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVisit', function() {
      it('should call updateVisit successfully', function(done) {
        //uncomment below and update the code to test updateVisit
        //instance.updateVisit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
