TRUNCATE TABLE services;
TRUNCATE TABLE specialities; 
TRUNCATE TABLE doctors;
TRUNCATE TABLE doctors_services;
TRUNCATE TABLE marks;
TRUNCATE TABLE offer_categories;
TRUNCATE TABLE time_table;
TRUNCATE TABLE doctors_timetables;
TRUNCATE TABLE visits;

-- INSERT INTO services (service_name) VALUES
--     ('Service 1'),

INSERT INTO services (service_name) VALUES
    ('Zastrzyk'),
    ('Pobieranie krwi'),
    ('Wykonanie EKG'),
    ('Wykonanie Echo serca'),
    ('Wykonanie badania cytologia'),
    ('Wykonanie badania prostaty'),
    ('Wykonanie badania BMI'),
    ('Podłączenie kroplówki');

INSERT INTO specialities (speciality_name) VALUES 
    ('Pielęgniarz/rka'),
    ('Kardiolog'),
    ('Neurolog'),
    ('Ginekolog'),
    ('Ortopeda'),
    ('Chirurg'),
    ('Laryngolog'),
    ('Psychiatra'),
    ('Okulista'),
    ('Lekarz rodzinny'),
    ('Dermatolog');

INSERT INTO doctor (doctor_first_name, doctor_last_name, degree, degree_short, speciality_id) VALUES 
    ('Anna', 'Lewandowska', 'Doktor', 'dr', 1),
    ('Joanna', 'Smugacz', 'Doktor', 'dr', 1),
    ('Anna', 'Talent', 'Doktor', 'dr', 2),
    ('Marzena', 'Antczak', 'Doktor', 'dr', 2),
    ('Małgorzata', 'Marach', 'Doktor', 'dr', 3),
    ('Patrycja', 'Kwiatkowska', 'Doktor', 'dr', 3),
    ('Alicja', 'Szczypkowska', 'Doktor', 'dr', 4),
    ('Marta', 'Kopiec', 'Doktor', 'dr', 4),
    ('Arkadiusz', 'Chrapkowski', 'Doktor', 'dr', 5),
    ('Gabriel', 'Godek', 'Doktor', 'dr', 5),
    ('Kamil', 'Spyrka', 'Doktor', 'dr', 6),
    ('Wioletta', 'Wasilewska', 'Doktor', 'dr', 6),
    ('Zenon', 'Romaniuk', 'Doktor', 'dr', 7),
    ('Adrianna', 'Kulik', 'Doktor', 'dr', 7),
    ('Łucja', 'Wasilewska', 'Doktor', 'dr', 8),
    ('Sebastian', 'Jachachan', 'Doktor', 'dr', 8),
    ('Pamela', 'Urbanowicz', 'Doktor', 'dr', 9),
    ('Zofia', 'Styrna', 'Doktor', 'dr', 9),
    ('Magdalena', 'Szukała', 'Doktor', 'dr', 10),
    ('Maria', 'Wałaszek', 'Doktor', 'dr', 10),
    ('Michał', 'Agatanek', 'Doktor', 'dr', 10),
    ('Michał', 'Mazurek', 'Doktor', 'dr', 11),
    ('Wiktoria', 'Jedlińska', 'Doktor', 'dr', 11);

INSERT INTO doctors_services (doctor_id, service_id) VALUES 
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (2, 4),
    (2, 1),
    (2, 2),
    (2, 3),
    (2, 4),
    (2, 5),
    (3, 6),
    (3, 7),
    (3, 8),
    (3, 1),
    (4, 1),
    (4, 2),
    (4, 3),
    (4, 4),
    (5, 4),
    (5, 1),
    (5, 2),
    (5, 3),
    (5, 4),
    (5, 5),
    (6, 6),
    (6, 7),
    (6, 8),
    (6, 1),
    (7, 1),
    (7, 2),
    (7, 3),
    (7, 4),
    (8, 4),
    (8, 1),
    (8, 2),
    (8, 3),
    (8, 4),
    (8, 5),
    (9, 6),
    (9, 7),
    (9, 8),
    (9, 1),
    (10, 1),
    (10, 2),
    (10, 3),
    (10, 4),
    (11, 4),
    (11, 1),
    (11, 2),
    (11, 3),
    (11, 4),
    (11, 5),
    (12, 6),
    (12, 7),
    (12, 8),
    (12, 1),
    (13, 1),
    (13, 2),
    (13, 3),
    (13, 4),
    (14, 4),
    (14, 1),
    (14, 2),
    (14, 3),
    (14, 4),
    (14, 5),
    (15, 6),
    (15, 7),
    (15, 8),
    (15, 1),
    (16, 2),
    (16, 3),
    (16, 4),
    (16, 5),
    (16, 6),
    (16, 7),
    (16, 8),
    (17, 1),
    (17, 2),
    (17, 3),
    (17, 4),
    (17, 5),
    (17, 6),
    (17, 7),
    (17, 8),
    (18, 1),
    (18, 2),
    (18, 3),
    (18, 4),
    (18, 5),
    (18, 6),
    (18, 7),
    (18, 8),
    (19, 1),
    (19, 2),
    (19, 3),
    (19, 4),
    (19, 5),
    (19, 6),
    (19, 7),
    (19, 8),
    (20, 1),
    (20, 2),
    (20, 3),
    (20, 4),
    (20, 5),
    (20, 6),
    (20, 7),
    (20, 8),
    (21, 1),
    (21, 2),
    (21, 3),
    (21, 4),
    (21, 5),
    (21, 6),
    (21, 7),
    (21, 8),
    (22, 1),
    (22, 2),
    (22, 3),
    (22, 4),
    (22, 5),
    (22, 6),
    (22, 7),
    (22, 8),
    (23, 1),
    (23, 2),
    (23, 3),
    (23, 4),
    (23, 5),
    (23, 6),
    (23, 7),
    (23, 8);

INSERT iNTO marks (title, description, comment, mark, doctor_id) VALUES 
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    1),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    2),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    3),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    4),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    5),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    6),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    6),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    7),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    8),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    9),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    10),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    11),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    12),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    13),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    14),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    15),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    16),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    17),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    18),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    19),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    20),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    21),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    22),
    ("Udana wizyta", 
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    "Lekarz bardzo mi pomógł. Wizyta przebiegła w miłej atmosferze. Lokalizacja placówki bardzo mi odpowiada. Wszystko jak najbardziej w porządku",
    5,
    23),
    ("Zawiedziony",
    "Przyszedłem z wielkimi oczekiwaniami, ale lekarz bardzo zlekceważył moje dolegliwości. Inny lekarz od razu wykrył, że przeszedłem zawał!",
    "Przyszedłem z wielkimi oczekiwaniami, ale lekarz bardzo zlekceważył moje dolegliwości. Inny lekarz od razu wykrył, że przeszedłem zawał!",
    1,
    3),
    ("Poprawna wizyta",
    "Zastrzyk w zaciszu domowym przebiegł gładko, jednak odejmuje gwiazdkę za godzinne spóźnienie.",
    "Zastrzyk w zaciszu domowym przebiegł gładko, jednak odejmuje gwiazdkę za godzinne spóźnienie.",
    4,
    1),
    ("Tragedia",
    "Gdzie ta kobieta uczyła się pobierać krew? Tragedia",
    "Gdzie ta kobieta uczyła się pobierać krew? Tragedia",
    2,
    2),
    ("Dziękuję",
    "Super kardiolog, teraz serce może bić w rytmie cha cha",
    "Super kardiolog, teraz serce może bić w rytmie cha cha",
    5,
    4),
    ("Ok",
    "Ok",
    "Ok",
    4,
    5),
    ("5/5",
    "Długo szukałam dobrego neurologa, teraz znalazłam",
    "Długo szukałam dobrego neurologa, teraz znalazłam",
    5,
    6),
    ("Polecam",
    "Moja córka zadowolona",
    "Moja córka zadowolona",
    5,
    7),
    ("Nie polecam",
    "Słabo poprowadzona ciąża",
    "Słabo poprowadzona ciąża",
    1,
    8),
    ("Cudownie","Po kontuzji nogi ani śladu","Po kontuzji nogi ani śladu",5,9),
    ("Pozytywnie","Minusem są wieczne opóźnienia, ale same wizyty ok","Minusem są wieczne opóźnienia, ale same wizyty ok",4,10),
    ("Słabo","Chamska wizyta, zero kultury","Chamska wizyta, zero kultury",2,11),
    ("Wyrostek","Chirurg bardzo mi pomógł z wyrostkiem robaczkowy","Chirurg bardzo mi pomógł z wyrostkiem robaczkowy",5,12),
    ("Odblokowane ucho",
    "Zapchane ucho, teraz dobrze słyszę",
    "Zapchane ucho, teraz dobrze słyszę",
    5,
    13),
    ("Słabe krople",
    "Przepisane krople tylko mnie uczuliły",
    "Przepisane krople tylko mnie uczuliły",
    3,
    14),
    ("Super","Wreszcie lekarz co nie żałować dać L4","Wreszcie lekarz co nie żałować dać L4",4,15),
    ("Napady lękowe","Dopadały mnie od dawna, dziękuję za dobre dobranie leków","Dopadały mnie od dawna, dziękuję za dobre dobranie leków",5,16),
    ("Lipa","Nadal jestem ślepa jak kret","Nadal jestem ślepa jak kret",1,17),
    ("Uratowana","Jaskrze mówię papa","Jaskrze mówię papa",5,18),
    ("Rewelacja","Rewelacja","Rewelacja",5,19),
    ("Dobrze było","Za pierwszym razem nie poszło, ale po większym wywiadze i drugiej wizycie było ok","Za pierwszym razem nie poszło, ale po większym wywiadze i drugiej wizycie było ok",4,20),
    ("Dobry wywiad","Dobry wywiad z pacjentem, ale średnie rezultaty","Dobry wywiad z pacjentem, ale średnie rezultaty",4,21),
    ("Syfy mam dalej","Po co chodzić do lekarza i brać leki jak nic się nie zmienia?","Po co chodzić do lekarza i brać leki jak nic się nie zmienia?",2,22),
    ("Dobrze",
    "Po wysypce ani śladu, super dermatolog",
    "Po wysypce ani śladu, super dermatolog",
    5,
    23),
    ("Serce",
    "Problemy z sercem mam od dziecka, ale taki brak profesjonalizmu pierwszy raz doświadczyłam!",
    "Problemy z sercem mam od dziecka, ale taki brak profesjonalizmu pierwszy raz doświadczyłam!",
    1,
    3),
    ("Domowa wizyta",
    "Polecam domowe wizyty, zawsze sprawnie",
    "Polecam domowe wizyty, zawsze sprawnie",
    5,
    1),
    ("Szybko",
    "Tak szybko zawsze można mi krew pobierać",
    "Tak szybko zawsze można mi krew pobierać",
    5,
    2),
    ("Ogólnie dobrze",
    "Zabieram tylko punkt za długie kolejki, może warto więcej czasu przeznaczać na wizytę przy umawianiu?",
    "Zabieram tylko punkt za długie kolejki, może warto więcej czasu przeznaczać na wizytę przy umawianiu?",
    4,
    4),
    ("Daje 3",
    "Można było inaczej wizytę poprowadzić, byłem u wielu specjalistów",
    "Można było inaczej wizytę poprowadzić, byłem u wielu specjalistów",
    3,
    5),
    ("Neurolog pierwsza klasa",
    "Ludzie tutaj warto przychodzić na wizyty!",
    "Ludzie tutaj warto przychodzić na wizyty!",
    5,
    6),
    ("Zadowoleni",
    "Super podejście do nastolatki",
    "Super podejście do nastolatki",
    5,
    7),
    ("Dobre badania",
    "Dobre prowadzenie mojej osoby",
    "Dobre prowadzenie mojej osoby",
    4,
    8),
    ("Dobrze",
    "Ręka jeszcze nie w pełni sprawna",
    "Ręka jeszcze nie w pełni sprawna",
    4,
    9),
    ("Dwója","Dwójka za wizytę, bo jedyny plus, że za darmo wizyta!",
    "Dwójka za wizytę, bo jedyny plus, że za darmo wizyta!",
    2,
    10),
    ("Kupiony dyplom",
    "Kto dał prawo do wykonywania zawodu? Słabo",
    "Kto dał prawo do wykonywania zawodu? Słabo",
    2,
    11),
    ("Uratowane życie",
    "Operacja ratująca życie, dziękuję",
    "Operacja ratująca życie, dziękuję",
    5,
    12),
    ("Ok",
    "Poprawnie, ale nie tego się spodziewałem",
    "Poprawnie, ale nie tego się spodziewałem",
    4,
    13),
    ("Słabo",
    "Nie podobało mi się",
    "Nie podobało mi się",
    4,
    14),
    ("Za szybko",
    "Czuję się jakby chodziło o jak najszybsze pozbycie się pacjenta",
    "Czuję się jakby chodziło o jak najszybsze pozbycie się pacjenta",
    2,
    15),
    ("Super pomoc",
    "Takich lekarzy nam potrzeba",
    "Takich lekarzy nam potrzeba",
    5,
    16),
    ("1/1",
    "Koszmarna wizyta, unikać!",
    "Koszmarna wizyta, unikać!",
    1,
    17),
    ("Okulista pierwsza klasa",
    "Dobrze dobrane szkła, dobrze widzę teraz",
    "Dobrze dobrane szkła, dobrze widzę teraz",
    5,
    18),
    ("Może być",
    "Może być",
    "Może być",
    4,
    19),
    ("Nie!",
    "Lekarz średniej klasy, jak można przeklinać przy pacjencie?",
    "Lekarz średniej klasy, jak można przeklinać przy pacjencie?",
    2,
    20),
    ("Dobry lekarz",
    "Szczegółowy wywiad",
    "Szczegółowy wywiad",
    5,21),
    ("Dobrze, ale drogie leki przepisane",
    "Dobrze, ale drogie leki przepisane","Dobrze, ale drogie leki przepisane",
    4,
    22),
    ("Lubię tu wracać",
    "Polecam serdecznie",
    "Polecam serdecznie",
    5,
    23);

INSERT INTO offer_categories (category_name) VALUES
("Domowe wizyty"),
("Kardiologia"),
("Dermatologia"),
("Neurologia"),
("Ginekologia"),
("Chirurgia"),
("Laryngologia"),
("Psychiatria"),
("Okulistyka"),
("Ortopedia"),
("Podstawowa opieka medyczna");

INSERT INTO offers (offer_name,offer_categories_id,promo,price,is_nfz,is_private_offer) VALUES
("Kroplówka",1,"-20%",100,false,true),
("Zastrzyk",1,NULL,75,false,true),
("Szczepienie",1,"-15%",200,true,true),
("Zmiana opatrunku",1,NULL,20,true,true),
("Zdejmowanie gipsu",1,NULL,20,true,true),
("Badanie EKG",2,NULL,100,true,true),
("Monitorowanie Holtera",2,NULL,75,true,true),
("Echokardiologia",2,"-10%",100,true,true),
("Ocena ryzyka sercowo-naczyniowego",2,NULL,100,true,true),
("Konsultacja kardiologiczna",2,NULL,200,true,true),
("Leczenie trądzika",3,"-10%",100,true,true),
("Usuwanie znamion",3,NULL,150,true,true),
("Terapia przeciwstarzeniowa",3,"-10%",400,false,true),
("Leczenie łuszczycy",3,NULL,200,true,true),
("Konsultacja dermatologiczna",3,NULL,100,true,true),
("Badanie neurologiczne",4,NULL,100,true,true),
("Leczenie migreny",4,NULL,50,true,true),
("Terapia chorób zwyrodnieniowych układu nerwowego",4,"-10%",350,false,true),
("Rehabilitacja po udarze",4,NULL,100,true,true),
("Konsultacja neurologiczna",4,NULL,300,false,true),
("Badanie ginekologiczne",5,NULL,150,true,true),
("Cytologia",5,NULL,250,true,true),
("Konsultacje prenatalne i opieka nad ciążą",5,"-10%",120,true,true),
("Leczenie i diagnoza chorób narządów płciowyuch damskich",5,NULL,100,true,true),
("Zabiegi ginekologiczne",5,NULL,400,true,true),
("Konsultacje przedoperacyjne",6,"-10%",100,true,true),
("Wykonanie zabiegów chirurgicznych",6,NULL,400,true,true),
("Usuwanie guzów",6,NULL,250,true,true),
("Konsultacja laryngologiczna",7,"-10%",120,true,true),
("Diagnoza i leczenie chorób gardła",7,NULL,100,true,true),
("Diagnoza i leczenie chorób nosa",7,NULL,100,true,true),
("Diagnoza i leczenie chorób uszu",7,"-10%",100,true,true),
("Terapia zaburzeń głosu",7,NULL,400,false,true),
("Usuwanie polipów",7,NULL,550,true,true),
("Zabiegi endoskopowe nosa i krtani",7,NULL,320,false,true),
("Konsultacja psychiatryczna",8,"-5%",120,true,true),
("Psychoterapia",8,NULL,200,true,true),
("Zarządzanie zaburzeniami lękowymi",8,NULL,150,true,true),
("Terapia uzależnień",8,NULL,500,false,true),
("Badanie wzroku",9,"-8%",200,true,true),
("Korekcja wzroku",9,NULL,450,false,true),
("Chirugia zaćmy",9,NULL,350,true,true),
("Dopasowanie okularów lub soczewek",9,NULL,10,true,true),
("Badanie ortopedyczne",10,NULL,250,true,true),
("Leczenie urazów",10,NULL,350,true,true),
("Rehabilitacja po kontuzjach sportowych",10,NULL,450,true,true),
("Leczenie chorób zwyrodnieniowych stawów",10,NULL,200,true,true),
("Artroskopia",10,NULL,350,true,true),
("Endoprotezoplastyka",10,"-10%",650,false,true),
("Badanie ogólne",11,NULL,50,true,true),
("Diagnoza i leczenie chorób",11,NULL,50,true,true),
("Profilaktyka chorób",11,NULL,20,true,true),
("Badanie ortopedyczne",11,NULL,250,true,true),
("Skierowanie do specjalistów",11,NULL,200,true,true),
("Konsultacja zdrowotna",11,NULL,450,true,true);
