/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.LocalTime();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LocalTime', function() {
    it('should create an instance of LocalTime', function() {
      // uncomment below and update the code to test LocalTime
      //var instance = new OpenApiDefinition.LocalTime();
      //expect(instance).to.be.a(OpenApiDefinition.LocalTime);
    });

    it('should have the property hour (base name: "hour")', function() {
      // uncomment below and update the code to test the property hour
      //var instance = new OpenApiDefinition.LocalTime();
      //expect(instance).to.be();
    });

    it('should have the property minute (base name: "minute")', function() {
      // uncomment below and update the code to test the property minute
      //var instance = new OpenApiDefinition.LocalTime();
      //expect(instance).to.be();
    });

    it('should have the property second (base name: "second")', function() {
      // uncomment below and update the code to test the property second
      //var instance = new OpenApiDefinition.LocalTime();
      //expect(instance).to.be();
    });

    it('should have the property nano (base name: "nano")', function() {
      // uncomment below and update the code to test the property nano
      //var instance = new OpenApiDefinition.LocalTime();
      //expect(instance).to.be();
    });

  });

}));
