/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.PostVisitDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostVisitDto', function() {
    it('should create an instance of PostVisitDto', function() {
      // uncomment below and update the code to test PostVisitDto
      //var instance = new OpenApiDefinition.PostVisitDto();
      //expect(instance).to.be.a(OpenApiDefinition.PostVisitDto);
    });

    it('should have the property doctorId (base name: "doctorId")', function() {
      // uncomment below and update the code to test the property doctorId
      //var instance = new OpenApiDefinition.PostVisitDto();
      //expect(instance).to.be();
    });

    it('should have the property timeTableId (base name: "timeTableId")', function() {
      // uncomment below and update the code to test the property timeTableId
      //var instance = new OpenApiDefinition.PostVisitDto();
      //expect(instance).to.be();
    });

    it('should have the property serviceId (base name: "serviceId")', function() {
      // uncomment below and update the code to test the property serviceId
      //var instance = new OpenApiDefinition.PostVisitDto();
      //expect(instance).to.be();
    });

    it('should have the property place (base name: "place")', function() {
      // uncomment below and update the code to test the property place
      //var instance = new OpenApiDefinition.PostVisitDto();
      //expect(instance).to.be();
    });

    it('should have the property refferalNumber (base name: "refferalNumber")', function() {
      // uncomment below and update the code to test the property refferalNumber
      //var instance = new OpenApiDefinition.PostVisitDto();
      //expect(instance).to.be();
    });

    it('should have the property home (base name: "home")', function() {
      // uncomment below and update the code to test the property home
      //var instance = new OpenApiDefinition.PostVisitDto();
      //expect(instance).to.be();
    });

    it('should have the property nfz (base name: "nfz")', function() {
      // uncomment below and update the code to test the property nfz
      //var instance = new OpenApiDefinition.PostVisitDto();
      //expect(instance).to.be();
    });

  });

}));
